development:
  adapter: postgresql
  encoding: unicode
  database: pretty_search
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: pretty_search_test
  pool: 5
  timeout: 5000